# Use an NVIDIA base image with CUDA.
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

# Install Python 3.10 and pip
RUN apt-get update && \
    apt-get install -y python3.10 python3-pip python3.10-venv && \
    ln -sf /usr/bin/python3.10 /usr/bin/python && \
    ln -sf /usr/bin/pip3 /usr/bin/pip

# Set the working directory in the container
WORKDIR /app

# Install PyTorch with CUDA 11.8  (Install PyTorch FIRST)
RUN pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu118

# Copy the requirements file into the container
COPY requirements.txt .

# Create and activate the virtual environment, and install other dependencies
RUN python -m venv venv && \
    . venv/bin/activate && \
    pip install --no-cache-dir -r requirements.txt
